language: objective-c
osx_image: xcode10.1
xcode_project: RMQClient.xcodeproj
xcode_scheme: RMQClient
before_install:
  - brew update
  - brew install rabbitmq
  - cp .travis/etc/* /usr/local/etc/rabbitmq/
  - cp TestCertificates/* /usr/local/etc/rabbitmq/
  - /usr/local/sbin/rabbitmq-plugins enable --offline rabbitmq_auth_mechanism_ssl
  - brew services start rabbitmq
before_script:
  - make bootstrap
  - until lsof -i:5672; do echo "Waiting for RabbitMQ to start..."; sleep 1; done
  - make before_build
  - make set_up_test_vhosts
  - make set_up_test_users
env:
  - TARGET=tests_ios TRAVIS_XCODE_SDK=iphonesimulator12.1 iOS_VERSION=12.1
  - TARGET=tests_macos TRAVIS_XCODE_SDK=macosx10.14
script: travis_retry make $TARGET iOS_VERSION=$iOS_VERSION
after_failure:
  - cat /usr/local/var/log/rabbitmq/rabbit@localhost.log
cache:
  directories:
  - Carthage
